CREATE DATABASE grocery_db;

USE grocery_db;

CREATE TABLE tbl_users (
	user_id VARCHAR(200) PRIMARY KEY DEFAULT UUID(),
    email VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tbl_groceries (
	grocery_id VARCHAR(200) PRIMARY KEY DEFAULT UUID(),
    title VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL,
    user_id VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES tbl_users(user_id)
);

CREATE TABLE tbl_grocery_items (
	item_id VARCHAR(200) PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(200) NOT NULL,
    qty INT DEFAULT 1,
    price DECIMAL(10, 2) NOT NULL,
    grocery_id VARCHAR(200) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (grocery_id) REFERENCES tbl_groceries (grocery_id)
);